extraction:
	./processOne.sh ./input.html ./output.xml && cat ./output.xml

extractions:
	./processAll.sh /media/webdav/vtc/licences/personne-physique/html /media/webdav/vtc/licences/personne-physique/xml/
